<?php

/**
 * @file
 * Contains mailermailer.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailermailer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailermailer module.
    case 'help.page.mailermailer':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides integration for MailerMailer with Webform.') . '</p>';
      return $output;

    default:
  }
}
